Curriculum-Recuperacion/Models/ContactoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Curriculum_Recuperacion.Models
{
    public class ContactoModel
    {
        public int IdContacto { get; set; }
        [Required(ErrorMessage ="El campo nombre es obligatorio")]
        public string? Nombre { get; set; }
        [Required(ErrorMessage = "El campo telefono es obligatorio")]
        public string? Telefono { get; set; }
        [Required(ErrorMessage = "El campo correo es obligatorio")]
        public string? Correo { get; set; }

        public string? Email { get; set; }
        public string? Foto { get; set; }
        public IFormFile Imagen { get; set; }
        public string? Titulo { get; set; }
        public List<ExperienciaLaboralModel> ExperienciaLaboral { get; set; }
        public List<EstudioModel> Estudios { get; set; }
        public List<SkillModel> Skills { get; set; }

    }

    public class ExperienciaLaboralModel
    {
        public string Puesto { get; set; }
        public string Empresa { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
    }

    public class EstudioModel
    {
        public string Nivel { get; set; }
        public string Institucion { get; set; }
        public string Descripcion { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaFin { get; set; }
    }

    public class SkillModel
    {
        public string Nombre { get; set; }
        public string Nivel { get; set; }
    }
}

Curriculum-Recuperacion/Models/ErrorViewModel.cs
namespace Curriculum_Recuperacion.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Curriculum-Recuperacion/Controllers/HomeController.cs
using Curriculum_Recuperacion.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Curriculum_Recuperacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult VerCurriculum() 
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Curriculum-Recuperacion/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using Curriculum_Recuperacion.Datos;
using Curriculum_Recuperacion.Models;

namespace Curriculum_Recuperacion.Controllers
{
    public class MantenedorController : Controller
    {

        ContactoDatos _ContactoDatos = new ContactoDatos();
        public IActionResult Listar()
        {
            //La vista mostrara una lista de los contactos
            var oLista = _ContactoDatos.Listar();
            return View(oLista);
        }

        public IActionResult Detalle(int IdContacto)
        {
            var contacto = _ContactoDatos.Obtener(IdContacto);

            if (contacto == null)
            {
                return NotFound();
            }

            return View(contacto);
        }



        public IActionResult Guardar()
        {
            //Metodo solo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(ContactoModel oContacto)
        {
            //Metodo recibe el objeto para guardarlo en la BD
            //if (!ModelState.IsValid)
            //    return View();

            var respuesta = _ContactoDatos.Guardar(oContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdContacto)
        {
            //Metodo solo devuelve la vista
            var ocontacto = _ContactoDatos.Obtener(IdContacto);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Editar(ContactoModel oContacto)
        {
            //Metodo solo devuelve la vista

            if (!ModelState.IsValid)
                return View();

            var respuesta = _ContactoDatos.Editar(oContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdContacto)
        {
            //Metodo solo devuelve la vista
            var ocontacto = _ContactoDatos.Obtener(IdContacto);
            return View(ocontacto);
        }

        [HttpPost]
        public IActionResult Eliminar(ContactoModel oContacto)
        {

            var respuesta = _ContactoDatos.Eliminar(oContacto.IdContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View("Listar");
        }


        public IActionResult Ver(int IdContacto)
        {
            var contacto = _ContactoDatos.Obtener(IdContacto);

            if (contacto == null)
            {
                // Si no se encuentra el contacto, puedes redirigir a una página de error o mostrar un mensaje
                return RedirectToAction("Error");
            }

            // Convertir la imagen a una representación base64
            

            return View(contacto);
        }
    }


    //public IActionResult VerCurriculum()
    //{

    //}
}

Curriculum-Recuperacion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Curriculum";
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <!-- Estilos personalizados -->
    <link rel="stylesheet" href="~/css/Estilo.css" />
</head>
<body>

    <div class="container text-center mt-5">
        <h1 class="display-4">Bienvenido a mi página</h1>

        <div class="about-me mt-4">
            <h2>Sobre mí:</h2>
            <p><strong>Nombre:</strong> Martin Enrique Aguilar Valencia</p>
            <p><strong>Grupo:</strong> 24BM</p>
            <p><strong>Página:</strong> Recuperación de programación WEB.</p>
        </div>

        <div class="resume-example mt-4">
            <h2>Ejemplo de cómo quedará tu currículum</h2>
            <img src="~/img/c567b4e0-dc42-461f-b070-9328c091b3a0.jpeg" alt="Descripción de la imagen">

            <h2 class="mt-4">No esperes más, crea tu propio currículum</h2>
            <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-primary mt-2">Crea tu propio currículum</a>
        </div>
    </div>

    <!-- Scripts de Bootstrap (asegúrate de tener Bootstrap instalado) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Curriculum-Recuperacion/Views/Mantenedor/Detalle.cshtml
@model Curriculum_Recuperacion.Models.ContactoModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="~/css/EstiloDetalle.css" />

    <title>Detalle</title>
</head>
<body>
    <section class="container mt-5">
        <div class="row">
            <div class="col-12">
                <h2 class="text-center">Detalle</h2>
            </div>
            <div class="col-6 mx-auto mt-4">
                <ul class="list-group">
                    <li class="list-group-item">Nombre: @Model.Nombre</li>
                    <li class="list-group-item">Titulo: @Model.Titulo</li>
                    <li class="list-group-item">Correo: @Model.Correo</li>
                    <li class="list-group-item">WebSite: @Model.Email</li>
                    <li class="list-group-item">Telefono: @Model.Telefono</li>
                    <li class="list-group-item">Foto: @Model.Foto</li>
                    <li class="list-group-item">
                        <img class="mx-auto d-block my-5" width="300" src="/uploads/@Model.Foto" />
                    </li>
                </ul>
            </div>
        </div>
    </section>
</body>
</html>

Curriculum-Recuperacion/Views/Mantenedor/Editar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Editar contacto</h5>
    <div class="card-body">
        <form asp-action="Editar" asp-controller="Mantenedor" method="post">
            <input asp-for="IdContacto" type="hidden" class="form-control" />
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Titulo</label>
                <input asp-for="Titulo" type="text" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Correo</label>
                <input asp-for="Correo" type="text" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">WebSite</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Foto</label>
                <input asp-for="Foto" type="file" class="form-control" placeholder="Tu imagen" id="Foto" name="Foto">
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Curriculum-Recuperacion/Views/Mantenedor/Eliminar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Eliminar Curriculum</h5>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="IdContacto" type="hidden" class="form-control"/>

            <div class="alert alert-danger" role="alert">
                ¿Deseas eliminar el curriculum: @Html.DisplayTextFor(m => m.Nombre)?
            </div>
            <button type="submit" class="btn btn-danger">Eliminar</button>

            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Curriculum-Recuperacion/Views/Mantenedor/Guardar.cshtml
@model ContactoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">Crear curriculum</h5>
    <div class="card-body">
        <form asp-action="Guardar" enctype="multipart/form-data" asp-controller="Mantenedor" method="post">
                <div class="mb-3">
                    <label class="form-label">Nombre</label>
                    <input asp-for="Nombre" type="text" class="form-control"/>   
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            <div class="mb-3">
                <label class="form-label">Titulo</label>
                <input asp-for="Titulo" type="text" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
                <div class="mb-3">
                    <label class="form-label">Telefono</label>
                    <input asp-for="Telefono" type="text" class="form-control">
                <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label">Correo</label>
                    <input asp-for="Correo" type="text" class="form-control">
                <span asp-validation-for="Correo" class="text-danger"></span>
                </div>
            <div class="mb-3">
                <label class="form-label">WebSite</label>
                <input asp-for="Email" type="text" class="form-control">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label">Foto</label>
                <input type="file" asp-for="Imagen" class="form-control" placeholder="Tu imagen">
                <span asp-validation-for="Imagen" class="text-danger mt-3 d-block"></span>
            </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Curriculum-Recuperacion/Views/Mantenedor/Listar.cshtml
@model List<ContactoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <h5 class="card-header">
        <i class="bi bi-card-list"></i>
        Lista curriculum
    </h5>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">
            <i class="bi bi-plus-circle"></i>
            Crear nuevo
        </a>
       <hr />
       <table class="table table-bordered">
           <thead>
               <tr>
                    <th>
                        <i class="bi bi-person-circle"></i>
                        Nombre
                    </th>
                    <th>
                        <i class="bi bi-person-workspace"></i>
                        Titulo
                    </th>
                    <th>
                        <i class="bi bi-telephone-fill"></i>
                        Telefono
                    </th>
                    <th>
                        <i class="bi bi-envelope"></i>
                        Correo
                    </th>
                    <th>
                        <i class="bi bi-browser-chrome"></i>
                        WebSite
                    </th>
                    <th>
                        <i class="bi bi-camera-fill"></i>
                        Foto
                    </th>
                   <th></th>
               </tr>
           </thead>
           <tbody>
                
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Nombre</td>
                            <td>@item.Titulo</td>
                            <td>@item.Telefono</td>
                            <td>@item.Correo</td>
                            <td>@item.Email</td>
                            <td>
                            <img src="@item.Foto" />
                            </td>
                            <td>
                                <a asp-action="Editar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" asp-route-IdContacto="@item.IdContacto">
                                    <i class="bi bi-pencil-square"></i>
                                    Editar
                                </a>
                                <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm" asp-route-IdContacto="@item.IdContacto">
                                    <i class="bi bi-x-circle"></i>
                                    Eliminar
                                </a>
                                <a asp-action="Detalle" asp-controller="Mantenedor" class="btn btn-outline-info btn-sm" asp-route-IdContacto="@item.IdContacto">
                                    Detalle
                                </a>
                                <a asp-action="Ver" asp-controller="Mantenedor" class="btn btn-outline-info btn-sm" asp-route-IdContacto="@item.IdContacto">
                                    Ver
                                </a>
                            </td>
                        </tr>
                    }
                
            </tbody>
       </table>
    </div>
</div>

Curriculum-Recuperacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Curriculum_Recuperacion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Curriculum_Recuperacion.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Curriculum_Recuperacion</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mantenedor" asp-action="Listar">Lista Curriculum</a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Curriculum_Recuperacion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>